//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alertas
    {
        public int id { get; set; }
        public byte vista { get; set; }
        public byte eliminada { get; set; }
        public string mensaje { get; set; }
        public string tipo_alerta { get; set; }
        public System.DateTime fecha_creada { get; set; }
        public string creador { get; set; }
        public string perfil_ver { get; set; }
        public string titulo { get; set; }
    }
}
