//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class capacitaciones
    {
        public int id { get; set; }
        public string periodo { get; set; }
        public string encargado { get; set; }
        public string tema { get; set; }
        public string comentarios { get; set; }
        public System.DateTime fecha { get; set; }
        public string nom_File { get; set; }
    }
}
