//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clases_sima
    {
        public clases_sima()
        {
            this.estudiantes_asistentes = new HashSet<estudiantes_asistentes>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string periodo { get; set; }
        public string tema { get; set; }
        public string comentario { get; set; }
        public int cursos_id { get; set; }
        public string usuarios_id { get; set; }
        public string evidencia { get; set; }
        public System.DateTime fecha_realizada { get; set; }
    
        public virtual cursos cursos { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<estudiantes_asistentes> estudiantes_asistentes { get; set; }
    }
}
