//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos_acargo
    {
        public int id { get; set; }
        public string idUsuario { get; set; }
        public string materia { get; set; }
        public string periodo { get; set; }
        public string id_grupo { get; set; }
        public int id_curso { get; set; }
        public string programa { get; set; }
    
        public virtual cursos cursos { get; set; }
        public virtual materias materias { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
