//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSima.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_simaEntitie : DbContext
    {
        public bd_simaEntitie()
            : base("name=bd_simaEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<calificaciones_periodo> calificaciones_periodo { get; set; }
        public DbSet<capacitaciones> capacitaciones { get; set; }
        public DbSet<clases_sima> clases_sima { get; set; }
        public DbSet<configuracion_app> configuracion_app { get; set; }
        public DbSet<cursos> cursos { get; set; }
        public DbSet<estudiantes_asistentes> estudiantes_asistentes { get; set; }
        public DbSet<grupos_acargo> grupos_acargo { get; set; }
        public DbSet<materias> materias { get; set; }
        public DbSet<Notas> Notas { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
