//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class preguntas_test
    {
        public preguntas_test()
        {
            this.pregunta_test_responder = new HashSet<pregunta_test_responder>();
        }
    
        public int id { get; set; }
        public string Pregunata { get; set; }
        public byte eliminado { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<pregunta_test_responder> pregunta_test_responder { get; set; }
    }
}
