//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuestas
    {
        public int id_preguntas_test_respustas { get; set; }
        public string id_persona { get; set; }
        public int punto { get; set; }
        public string observacion { get; set; }
    
        public virtual pregunta_test_responder pregunta_test_responder { get; set; }
    }
}
