//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.clases_sima = new HashSet<clases_sima>();
            this.cursos = new HashSet<cursos>();
            this.grupos_acargo = new HashSet<grupos_acargo>();
            this.Test = new HashSet<Test>();
        }
    
        public string id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string correo { get; set; }
        public string celular { get; set; }
        public string tipo { get; set; }
        public string contrasena { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<byte> eliminado { get; set; }
    
        public virtual ICollection<clases_sima> clases_sima { get; set; }
        public virtual ICollection<cursos> cursos { get; set; }
        public virtual ICollection<grupos_acargo> grupos_acargo { get; set; }
        public virtual ICollection<Test> Test { get; set; }
    }
}
